apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-database
  labels:
    app: billing-database
spec:
  replicas: 1
  serviceName: billing-database-service
  selector:
    matchLabels:
      app: billing-database
  template:
    metadata:
      labels:
        app: billing-database
    spec:
      restartPolicy: "Always"
      containers:
        - name: billing-database
          image: postgres:13.9-alpine
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: billing-db-volume
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d/init.sql
              readOnly: true
              subPath: init.sql
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: billing-db-secret
                  key: billing-db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-db-secret
                  key: billing-db-password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: billing-configmap
                  key: billing_database_name
          resources:
            limits:
              cpu: 150m
              memory: 500Mi
      volumes:
        - name: billing-db-volume
          # persistentVolumeClaim:
          #   claimName: billing-db-volume
          hostPath:
            path: "/database/billing" # Path from the host
        - name: init-scripts
          configMap:
            name: billing-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: billing-database-service
spec:
  selector:
    app: billing-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: billing-db-volume
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
